name: kekiku
description: "Cake for you"
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  # Core
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.6
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  getwidget: ^6.0.0
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  cloud_firestore: ^5.6.6

  # Utils
  flutter_gen: ^5.10.0
  flutter_dotenv: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.3.0
  flutter_screenutil: ^5.9.3
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.5
  flutter_downloader: ^1.12.0
  tap_debouncer: ^2.2.0
  talker_dio_logger: ^4.7.1
  url_launcher: ^6.3.1
  device_info_plus: ^11.3.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  oktoast: ^3.4.0

  # Network
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dio_cookie_manager: ^3.2.0
  cached_network_image: ^3.4.1
  http_parser: ^4.1.2

  # Design
  flutter_form_builder: ^10.0.1
  flutter_svg: ^2.0.17
  pull_to_refresh: ^2.0.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  video_player: ^2.9.5
  animated_text_kit: ^4.2.3
  lottie: ^3.3.1
  infinite_scroll_pagination: ^5.0.0
  gif: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  mockito: ^5.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/fonts/montserrat/
    - assets/fonts/poppins/
    - assets/illustrations/
    - assets/jsons/
    - assets/lotties/
    - assets/images/
    - assets/svgs/
    - assets/gifs/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ff00ff"
  image: "assets/logo.png"
  android_12:
    color: "#ff00ff"
    image: "assets/logo.png"
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/icon/android/logo.png"
  android: true
  ios: true
